import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { brand } from '@/config/brand';
export function AllianceSection() {
    return (_jsxs("section", { className: "relative overflow-hidden py-20 bg-gradient-to-b from-white via-neutral-50 to-white", children: [_jsx("div", { className: "absolute top-20 left-10 w-32 h-32 bg-primary-200 rounded-full opacity-30 blur-2xl animate-pulse" }), _jsx("div", { className: "absolute bottom-20 right-10 w-40 h-40 bg-accent-200 rounded-full opacity-30 blur-2xl animate-pulse", style: { animationDelay: '1s' } }), _jsxs("div", { className: "container mx-auto px-4 relative z-10", children: [_jsx("div", { className: "text-center mb-16", children: _jsxs("h2", { className: "text-4xl md:text-5xl lg:text-6xl font-black mb-4", children: [_jsx("span", { className: "block text-primary-800 uppercase", children: "LA ALIANZA IDEAL" }), _jsx("span", { className: "block text-accent-600 mt-2", children: "PARA ALCANZAR EL M\u00C1XIMO" }), _jsx("span", { className: "block text-transparent bg-clip-text bg-gradient-to-r mt-2", style: {
                                        backgroundImage: `linear-gradient(135deg, ${brand.colors.primary[600]}, ${brand.colors.accent[500]})`,
                                    }, children: "POTENCIAL DIGITAL" })] }) }), _jsxs("div", { className: "relative h-96 md:h-[500px] max-w-4xl mx-auto mb-12", children: [_jsxs("div", { className: "absolute inset-0 flex items-center justify-center", children: [_jsx("div", { className: "absolute w-full h-64 border-2 rounded-full opacity-20", style: {
                                            borderImage: `linear-gradient(90deg, ${brand.colors.primary[400]}, ${brand.colors.accent[500]}) 1`,
                                            borderStyle: 'dashed',
                                        } }), _jsx("div", { className: "absolute w-3/4 h-48 border-2 rounded-full opacity-30", style: {
                                            borderImage: `linear-gradient(90deg, ${brand.colors.primary[400]}, ${brand.colors.accent[500]}) 1`,
                                            borderStyle: 'dashed',
                                        } })] }), _jsxs("svg", { className: "absolute inset-0 w-full h-full", viewBox: "0 0 1000 500", preserveAspectRatio: "none", children: [_jsx("defs", { children: _jsxs("linearGradient", { id: "lineGradient", x1: "0%", y1: "0%", x2: "100%", y2: "0%", children: [_jsx("stop", { offset: "0%", stopColor: brand.colors.primary[400], stopOpacity: "1" }), _jsx("stop", { offset: "100%", stopColor: brand.colors.accent[500], stopOpacity: "1" })] }) }), _jsx("path", { d: "M200,250 Q500,180 800,250", stroke: "url(#lineGradient)", strokeWidth: "3", fill: "none", className: "animate-pulse" }), _jsx("path", { d: "M200,250 Q500,320 800,250", stroke: "url(#lineGradient)", strokeWidth: "3", fill: "none", className: "animate-pulse", style: { animationDelay: '0.5s' } })] }), _jsx("div", { className: "absolute left-[10%] top-1/2 -translate-y-1/2", children: _jsx("div", { className: "bg-white p-6 rounded-2xl shadow-xl transform hover:scale-110 transition-transform", children: _jsx("img", { src: "https://federaciondecoaching.com/wp-content/uploads/2021/09/180.55-01.png", alt: "ICFM", className: "w-32 h-auto" }) }) }), _jsx("div", { className: "absolute right-[10%] top-1/2 -translate-y-1/2", children: _jsx("div", { className: "bg-white p-6 rounded-2xl shadow-xl transform hover:scale-110 transition-transform", children: _jsx("img", { src: brand.company.logo.main, alt: "IDSV", className: "w-32 h-auto" }) }) }), _jsx("div", { className: "absolute top-1/4 left-1/4 w-4 h-4 bg-primary-400 rounded-full animate-ping" }), _jsx("div", { className: "absolute bottom-1/4 left-1/3 w-3 h-3 bg-accent-400 rounded-full animate-ping", style: { animationDelay: '1s' } }), _jsx("div", { className: "absolute top-1/3 right-1/4 w-3 h-3 bg-primary-500 rounded-full animate-ping", style: { animationDelay: '2s' } })] }), _jsx("div", { className: "text-center max-w-3xl mx-auto", children: _jsxs("p", { className: "text-xl md:text-2xl text-neutral-700 leading-relaxed", children: ["La ", _jsx("strong", { className: "text-primary-700", children: "sinergia perfecta" }), " entre", ' ', _jsx("strong", { children: "ICFM" }), " e ", _jsx("strong", { children: "IDSV" }), " crea un", ' ', _jsx("span", { className: "font-bold bg-clip-text text-transparent", style: {
                                        backgroundImage: `linear-gradient(135deg, ${brand.colors.primary[600]}, ${brand.colors.accent[500]})`,
                                    }, children: "sistema orbital digital" }), ' ', "dise\u00F1ado para potenciar el", ' ', _jsx("strong", { className: "text-primary-700", children: "crecimiento profesional" }), " de coaches y mentores."] }) })] })] }));
}
