import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Rocket } from 'lucide-react';
import { brand } from '@/config/brand';
export function BoostSection() {
    return (_jsx("section", { className: "relative overflow-hidden py-8 bg-gradient-to-b from-neutral-100 to-white", children: _jsx("div", { className: "container mx-auto px-4", children: _jsxs("div", { className: "flex flex-col lg:flex-row items-center min-h-[80vh] py-12 relative", children: [_jsxs("div", { className: "flex-1 relative h-full min-h-[600px] flex justify-center items-center z-[2] overflow-visible", children: [_jsx("div", { className: "absolute w-[90%] h-[60%] left-[5%] top-[20%] rounded-[60%_40%_70%_30%_/_50%_60%_40%_50%] shadow-2xl animate-pulse", style: {
                                    background: `linear-gradient(135deg, ${brand.colors.primary[500]}, ${brand.colors.primary[700]})`,
                                    boxShadow: '0 40px 80px rgba(0, 44, 95, 0.4)',
                                } }), _jsx("div", { className: "absolute w-44 h-44 bg-gradient-to-br from-accent-500 to-accent-600 rounded-full opacity-70 top-[5%] left-[5%] animate-bounce", style: { animationDuration: '15s' } }), _jsx("div", { className: "absolute w-44 h-44 bg-gradient-to-br from-neutral-100 to-white rounded-full opacity-90 bottom-[5%] right-[5%] animate-bounce", style: { animationDuration: '12s', animationDelay: '3s' } }), _jsx("img", { src: "https://federaciondecoaching.com/wp-content/uploads/2025/04/slide-2-scaled.jpg", alt: "Boost", className: "relative z-10 w-[70%] max-w-lg h-auto object-contain drop-shadow-2xl animate-float", style: {
                                    filter: 'drop-shadow(0 25px 50px rgba(0, 0, 0, 0.5))',
                                } })] }), _jsxs("div", { className: "flex-1 px-4 lg:px-12 relative z-[3] mt-12 lg:mt-0", children: [_jsx("h2", { className: "text-4xl md:text-5xl lg:text-6xl font-black leading-tight text-primary-800 mb-6 uppercase", children: "IMPULSA" }), _jsx("h3", { className: "text-4xl md:text-5xl font-black leading-tight mb-6", children: _jsx("span", { className: "bg-gradient-to-r bg-clip-text text-transparent", style: {
                                        backgroundImage: `linear-gradient(135deg, ${brand.colors.primary[500]}, ${brand.colors.primary[700]})`,
                                        WebkitBackgroundClip: 'text',
                                        WebkitTextFillColor: 'transparent',
                                    }, children: "TU MARCA" }) }), _jsx("p", { className: "text-xl text-accent-600 italic font-semibold mb-6 inline-block", children: "Al siguiente nivel" }), _jsxs("div", { className: "space-y-4 text-lg text-neutral-700", children: [_jsx("p", { children: "Con las herramientas m\u00E1s avanzadas y un equipo experto, llevamos tu presencia digital al siguiente nivel." }), _jsx("p", { children: "Dise\u00F1o profesional, rendimiento optimizado y resultados que marcan la diferencia." })] }), _jsxs("div", { className: "mt-8 flex items-center gap-4", children: [_jsx(Rocket, { className: "w-12 h-12 text-accent-500" }), _jsx("span", { className: "text-xl font-bold text-primary-700", children: "Tecnolog\u00EDa de vanguardia" })] })] })] }) }) }));
}
