import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Zap, Clock } from 'lucide-react';
import { Button } from '../ui/Button';
import { brand } from '@/config/brand';
export function OfferSection() {
    return (_jsxs("section", { className: "relative overflow-hidden py-16 bg-gradient-to-br from-primary-50 via-white to-accent-50", children: [_jsx("div", { className: "absolute top-0 left-0 w-64 h-64 bg-primary-200 rounded-full opacity-20 blur-3xl" }), _jsx("div", { className: "absolute bottom-0 right-0 w-96 h-96 bg-accent-200 rounded-full opacity-20 blur-3xl" }), _jsxs("div", { className: "container mx-auto px-4 relative z-10", children: [_jsx("div", { className: "text-center mb-12", children: _jsx("h2", { className: "text-5xl md:text-6xl font-black text-primary-800 uppercase mb-4", children: "OFERTA \u00DANICA" }) }), _jsxs("div", { className: "grid md:grid-cols-2 gap-12 items-center max-w-5xl mx-auto", children: [_jsxs("div", { className: "text-center md:text-left", children: [_jsx("div", { className: "bg-gradient-to-br from-primary-600 to-primary-700 text-white px-8 py-6 rounded-2xl shadow-xl mb-6 inline-block", children: _jsx("h3", { className: "text-2xl font-bold uppercase tracking-wide", children: "ALOJAMIENTO + DOMINIO" }) }), _jsx("div", { className: "inline-block", children: _jsx("div", { className: "px-8 py-4 rounded-full text-white font-black text-2xl uppercase shadow-lg transform rotate-[-5deg]", style: {
                                                background: `linear-gradient(135deg, ${brand.colors.accent[500]}, ${brand.colors.accent[600]})`,
                                            }, children: "GRATIS" }) })] }), _jsxs("div", { className: "text-center", children: [_jsxs("h3", { className: "text-3xl md:text-4xl font-black text-primary-800 mb-8 uppercase", children: [_jsx("span", { className: "text-accent-600", children: "OBT\u00C9N" }), ' ', _jsx("span", { className: "text-primary-600", children: "HOY" }), " TU", ' ', _jsx("span", { className: "text-accent-600", children: "WEB" })] }), _jsx("div", { className: "relative inline-block p-8 rounded-3xl shadow-2xl transform hover:scale-105 transition-transform duration-300", style: {
                                            background: `linear-gradient(135deg, ${brand.colors.primary[500]}, ${brand.colors.primary[700]})`,
                                        }, children: _jsxs("div", { className: "text-white", children: [_jsx("div", { className: "text-lg font-bold uppercase mb-2 opacity-90", children: "SOLO POR" }), _jsx("div", { className: "text-4xl font-black uppercase mb-2", children: "OFERTA" }), _jsxs("div", { className: "text-7xl font-black mb-2", children: ["79,99", _jsx("span", { className: "text-4xl", children: "$" })] }), _jsx("div", { className: "text-xl font-bold uppercase opacity-90", children: "UN SOLO PAGO" })] }) })] })] }), _jsxs("div", { className: "text-center mt-12", children: [_jsxs(Button, { variant: "danger", size: "lg", className: "px-10 py-6 text-xl font-bold uppercase shadow-xl hover:shadow-2xl", children: [_jsx(Zap, { className: "mr-2 w-6 h-6" }), "QUIERO APROVECHAR ESTA OFERTA"] }), _jsxs("p", { className: "mt-4 text-neutral-600 flex items-center justify-center gap-2", children: [_jsx(Clock, { className: "w-5 h-5" }), _jsx("span", { className: "font-semibold", children: "Oferta v\u00E1lida solo por tiempo limitado" })] })] })] })] }));
}
