import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { Menu, X } from 'lucide-react';
import { useState } from 'react';
import { Button } from '../ui/Button';
export function Header() {
    const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
    return (_jsx("header", { className: "bg-white shadow-sm border-b border-gray-200 sticky top-0 z-50", children: _jsxs("div", { className: "container mx-auto px-4", children: [_jsxs("div", { className: "flex items-center justify-between h-16", children: [_jsxs(Link, { to: "/", className: "flex items-center space-x-2", children: [_jsx("div", { className: "w-8 h-8 bg-primary-600 rounded-lg flex items-center justify-center", children: _jsx("span", { className: "text-white font-bold text-lg", children: "C" }) }), _jsx("span", { className: "text-xl font-bold text-gray-900", children: "Cotizaciones IDSV" })] }), _jsxs("nav", { className: "hidden md:flex items-center space-x-6", children: [_jsx(Link, { to: "/", className: "text-gray-700 hover:text-primary-600 transition-colors font-medium", children: "Inicio" }), _jsx(Link, { to: "/about", className: "text-gray-700 hover:text-primary-600 transition-colors font-medium", children: "Acerca de" }), _jsx(Link, { to: "/invoice", className: "text-gray-700 hover:text-primary-600 transition-colors font-medium", children: "Factura" }), _jsx(Link, { to: "/landing", className: "text-gray-700 hover:text-primary-600 transition-colors font-medium", children: "Landing" }), _jsx(Link, { to: "/oferta-web-coaching", className: "text-gray-700 hover:text-primary-600 transition-colors font-medium", children: "Oferta Web Coaching" }), _jsx(Button, { variant: "primary", size: "sm", children: "Nuevo Proyecto" })] }), _jsx("button", { className: "md:hidden p-2 rounded-md text-gray-700 hover:bg-gray-100", onClick: () => setMobileMenuOpen(!mobileMenuOpen), "aria-label": "Toggle menu", children: mobileMenuOpen ? _jsx(X, { size: 24 }) : _jsx(Menu, { size: 24 }) })] }), mobileMenuOpen && (_jsxs("nav", { className: "md:hidden pb-4 space-y-2 animate-slide-up", children: [_jsx(Link, { to: "/", className: "block px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-md transition-colors", onClick: () => setMobileMenuOpen(false), children: "Inicio" }), _jsx(Link, { to: "/about", className: "block px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-md transition-colors", onClick: () => setMobileMenuOpen(false), children: "Acerca de" }), _jsx(Link, { to: "/invoice", className: "block px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-md transition-colors", onClick: () => setMobileMenuOpen(false), children: "Factura" }), _jsx(Link, { to: "/landing", className: "block px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-md transition-colors", onClick: () => setMobileMenuOpen(false), children: "Landing" }), _jsx(Link, { to: "/oferta-web-coaching", className: "block px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-md transition-colors", onClick: () => setMobileMenuOpen(false), children: "Oferta Web Coaching" }), _jsx("div", { className: "px-4 pt-2", children: _jsx(Button, { variant: "primary", size: "sm", fullWidth: true, children: "Nuevo Proyecto" }) })] }))] }) }));
}
