import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { Input } from '../components/ui/Input';
import { Modal } from '../components/ui/Modal';
import { Badge } from '../components/ui/Badge';
import { Plus, Filter } from 'lucide-react';
export function Home() {
    const [isModalOpen, setIsModalOpen] = useState(false);
    return (_jsxs("div", { className: "space-y-6 animate-fade-in", children: [_jsxs("div", { className: "flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-3xl font-bold text-gray-900", children: "Cotizaciones" }), _jsx("p", { className: "text-gray-600 mt-1", children: "Gestiona tus cotizaciones de manera eficiente" })] }), _jsxs(Button, { variant: "primary", size: "lg", onClick: () => setIsModalOpen(true), className: "flex items-center gap-2", children: [_jsx(Plus, { size: 20 }), "Nueva Cotizaci\u00F3n"] })] }), _jsx(Card, { children: _jsxs("div", { className: "flex flex-col sm:flex-row gap-4", children: [_jsx("div", { className: "flex-1", children: _jsx(Input, { placeholder: "Buscar cotizaciones...", className: "pl-10" }) }), _jsxs(Button, { variant: "outline", className: "flex items-center gap-2", children: [_jsx(Filter, { size: 18 }), "Filtros"] })] }) }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6", children: [1, 2, 3, 4, 5, 6].map((item) => (_jsxs(Card, { hover: true, className: "flex flex-col", children: [_jsx(CardHeader, { children: _jsxs("div", { className: "flex justify-between items-start", children: [_jsxs(CardTitle, { children: ["Cotizaci\u00F3n #", item] }), _jsx(Badge, { variant: item % 2 === 0 ? 'success' : 'warning', children: item % 2 === 0 ? 'Activa' : 'Pendiente' })] }) }), _jsxs(CardContent, { className: "flex-1", children: [_jsxs("p", { className: "text-gray-600 mb-2", children: ["Cliente: Cliente Ejemplo ", item] }), _jsxs("p", { className: "text-gray-600 mb-2", children: ["Fecha: ", new Date().toLocaleDateString('es-ES')] }), _jsxs("p", { className: "text-2xl font-bold text-primary-600 mt-4", children: ["$1,234.", item, "0"] })] }), _jsx(CardFooter, { children: _jsxs("div", { className: "flex gap-2 w-full", children: [_jsx(Button, { variant: "outline", size: "sm", className: "flex-1", children: "Ver Detalles" }), _jsx(Button, { variant: "primary", size: "sm", className: "flex-1", children: "Editar" })] }) })] }, item))) }), _jsx(Modal, { isOpen: isModalOpen, onClose: () => setIsModalOpen(false), title: "Nueva Cotizaci\u00F3n", size: "lg", children: _jsxs("div", { className: "space-y-4", children: [_jsx(Input, { label: "Cliente", placeholder: "Nombre del cliente" }), _jsx(Input, { label: "Descripci\u00F3n", placeholder: "Descripci\u00F3n del proyecto" }), _jsx(Input, { label: "Monto", type: "number", placeholder: "0.00" }), _jsxs("div", { className: "flex justify-end gap-3 pt-4", children: [_jsx(Button, { variant: "outline", onClick: () => setIsModalOpen(false), children: "Cancelar" }), _jsx(Button, { variant: "primary", onClick: () => setIsModalOpen(false), children: "Crear Cotizaci\u00F3n" })] })] }) })] }));
}
